Style:
  TrailingCommaInLiteral:
    Enabled: false
  Documentation:
    Enabled: false
  FrozenStringLiteralComment:
    Enabled: false
  IndentationConsistency:
    AllowProtectedAndPrivateMethodsBeIndented: true
