language: ruby
notifications:
  email: false
rvm:
  - 2.5.0
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libavahi-compat-libdnssd-dev
    - os: osx
      osx_image: xcode9.1
