language: ruby
cache: bundler

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  - gem update --system
  - gem --version
  - gem install bundler -v 1.16.1
  - bundle --version
  - bundle
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

rvm:
  - 2.4.3
  - 2.5.0
  - ruby-head

matrix:
  fast_finish: true

notifications:
  email: false
